"""Bootstrap starter Notion pages via MCP on first run."""

from __future__ import annotations

from codebase_cortex.config import Settings
from codebase_cortex.utils.logging import get_logger

logger = get_logger()

STARTER_PAGES = [
    {
        "title": "Architecture Overview",
        "icon": "🏗️",
        "description": "System design, component relationships, and architectural decisions.",
    },
    {
        "title": "API Reference",
        "icon": "📡",
        "description": "Endpoints, schemas, contracts, and integration points.",
    },
    {
        "title": "Knowledge Map",
        "icon": "🗺️",
        "description": "Topic clusters derived from code embeddings. Auto-generated.",
    },
    {
        "title": "Sprint Log",
        "icon": "📋",
        "description": "Weekly auto-generated summaries of code changes and documentation updates.",
    },
    {
        "title": "Task Board",
        "icon": "✅",
        "description": "Undocumented areas, documentation debt, and improvement tasks.",
    },
]


async def bootstrap_notion_pages(settings: Settings) -> list[dict]:
    """Create the starter Notion pages via MCP tools.

    Args:
        settings: Application settings with Notion token path.

    Returns:
        List of created page info dicts with page_id and title.
    """
    from codebase_cortex.mcp_client import notion_mcp_session
    from codebase_cortex.utils.rate_limiter import NotionRateLimiter

    rate_limiter = NotionRateLimiter()
    created_pages = []

    async with notion_mcp_session(settings) as session:
        for page_info in STARTER_PAGES:
            await rate_limiter.acquire()

            try:
                # Use MCP create_page tool
                result = await session.call_tool(
                    "notion_create_page",
                    arguments={
                        "title": f"{page_info['icon']} {page_info['title']}",
                        "content": f"# {page_info['title']}\n\n{page_info['description']}\n\n---\n*Auto-generated by Codebase Cortex*",
                    },
                )

                page_data = {
                    "title": page_info["title"],
                    "page_id": getattr(result, "text", str(result)),
                }
                created_pages.append(page_data)
                logger.info(f"Created page: {page_info['icon']} {page_info['title']}")

            except Exception as e:
                logger.error(f"Failed to create page '{page_info['title']}': {e}")

    return created_pages
