"""Tests for CLI commands (v0.2)."""

from __future__ import annotations

import json
from pathlib import Path

from click.testing import CliRunner

from codebase_cortex.cli import cli


def _init_cortex(tmp_path: Path) -> None:
    """Create a minimal .cortex/ directory for testing."""
    cortex_dir = tmp_path / ".cortex"
    cortex_dir.mkdir()
    (cortex_dir / ".env").write_text(
        "LLM_MODEL=google/gemini-2.5-flash-lite\n"
        "DOC_OUTPUT=local\n"
        "DOC_DETAIL_LEVEL=standard\n"
        "DOC_STRATEGY=main-only\n"
        "DOC_OUTPUT_MODE=apply\n"
    )


def _init_docs(tmp_path: Path) -> None:
    """Create a docs/ directory with sample files."""
    docs_dir = tmp_path / "docs"
    docs_dir.mkdir(exist_ok=True)
    (docs_dir / "INDEX.md").write_text("# Docs\n")
    (docs_dir / ".cortex-meta.json").write_text(json.dumps({
        "pages": {},
        "run_metrics": {},
    }))


# --- cortex config ---


def test_config_show(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    _init_cortex(tmp_path)

    runner = CliRunner()
    result = runner.invoke(cli, ["config", "show"])
    assert result.exit_code == 0
    assert "LLM_MODEL" in result.output


def test_config_set(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    _init_cortex(tmp_path)

    runner = CliRunner()
    result = runner.invoke(cli, ["config", "set", "DOC_DETAIL_LEVEL", "comprehensive"])
    assert result.exit_code == 0
    assert "DOC_DETAIL_LEVEL=comprehensive" in result.output

    # Verify it was written
    content = (tmp_path / ".cortex" / ".env").read_text()
    assert "DOC_DETAIL_LEVEL=comprehensive" in content


def test_config_set_new_key(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    _init_cortex(tmp_path)

    runner = CliRunner()
    result = runner.invoke(cli, ["config", "set", "DOC_SCOPE", "src/"])
    assert result.exit_code == 0

    content = (tmp_path / ".cortex" / ".env").read_text()
    assert "DOC_SCOPE=src/" in content


# --- cortex accept ---


def test_accept_no_drafts(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    _init_docs(tmp_path)

    runner = CliRunner()
    result = runner.invoke(cli, ["accept"])
    assert result.exit_code == 0
    assert "No draft banners" in result.output


def test_accept_removes_draft_banners(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    docs_dir = tmp_path / "docs"
    docs_dir.mkdir()
    (docs_dir / "arch.md").write_text(
        "> **[DRAFT]** Generated by Cortex. Run `cortex accept` to finalize.\n\n"
        "## Overview\nContent here.\n"
    )

    runner = CliRunner()
    result = runner.invoke(cli, ["accept"])
    assert result.exit_code == 0
    assert "Accepted" in result.output

    content = (docs_dir / "arch.md").read_text()
    assert "[DRAFT]" not in content
    assert "## Overview" in content


# --- cortex diff / apply / discard ---


def test_diff_no_proposed(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    _init_cortex(tmp_path)

    runner = CliRunner()
    result = runner.invoke(cli, ["diff"])
    assert result.exit_code == 0
    assert "No proposed changes" in result.output


def test_apply_no_proposed(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    _init_cortex(tmp_path)

    runner = CliRunner()
    result = runner.invoke(cli, ["apply"])
    assert result.exit_code == 0
    assert "No proposed changes" in result.output


def test_discard_no_proposed(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    _init_cortex(tmp_path)

    runner = CliRunner()
    result = runner.invoke(cli, ["discard"])
    assert result.exit_code == 0
    assert "No proposed changes" in result.output


def test_apply_copies_proposed(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    _init_cortex(tmp_path)

    # Create proposed/
    proposed_dir = tmp_path / ".cortex" / "proposed"
    proposed_dir.mkdir(parents=True)
    (proposed_dir / "arch.md").write_text("# Architecture\nNew content.\n")

    docs_dir = tmp_path / "docs"
    docs_dir.mkdir()

    runner = CliRunner()
    result = runner.invoke(cli, ["apply"])
    assert result.exit_code == 0
    assert "Applied" in result.output

    # Verify file was copied
    assert (docs_dir / "arch.md").exists()
    assert "New content" in (docs_dir / "arch.md").read_text()
    # Proposed dir should be cleaned up
    assert not proposed_dir.exists()


def test_discard_removes_proposed(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    _init_cortex(tmp_path)

    proposed_dir = tmp_path / ".cortex" / "proposed"
    proposed_dir.mkdir(parents=True)
    (proposed_dir / "arch.md").write_text("# Discardable\n")

    runner = CliRunner()
    result = runner.invoke(cli, ["discard"])
    assert result.exit_code == 0
    assert "Discarded" in result.output
    assert not proposed_dir.exists()


# --- cortex resolve ---


def test_resolve_no_conflicts(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    docs_dir = tmp_path / "docs"
    docs_dir.mkdir()
    (docs_dir / "readme.md").write_text("# Clean file\n")

    runner = CliRunner()
    result = runner.invoke(cli, ["resolve"])
    assert result.exit_code == 0
    assert "No conflict markers" in result.output


def test_resolve_fixes_conflicts(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    docs_dir = tmp_path / "docs"
    docs_dir.mkdir()
    (docs_dir / "api.md").write_text(
        "# API\n"
        "<<<<<<< HEAD\n"
        "old content\n"
        "=======\n"
        "new content\n"
        ">>>>>>> branch\n"
        "rest of file\n"
    )

    runner = CliRunner()
    result = runner.invoke(cli, ["resolve"])
    assert result.exit_code == 0
    assert "Resolved" in result.output

    content = (docs_dir / "api.md").read_text()
    assert "<<<<<<" not in content
    assert "new content" in content


# --- cortex status ---


def test_status_not_initialized(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

    runner = CliRunner()
    result = runner.invoke(cli, ["status"])
    assert "Not initialized" in result.output


def test_status_initialized(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    _init_cortex(tmp_path)
    _init_docs(tmp_path)

    runner = CliRunner()
    result = runner.invoke(cli, ["status"])
    assert result.exit_code == 0
    assert "local" in result.output
    assert "standard" in result.output
