"""DocWriter agent — generates documentation updates via DocBackend."""

from __future__ import annotations

from codebase_cortex.agents.base import BaseAgent
from codebase_cortex.backends import get_backend
from codebase_cortex.state import CortexState, DocUpdate
from codebase_cortex.utils.json_parsing import parse_json_array

DRAFT_BANNER = (
    "> :warning: **Draft — generated by Codebase Cortex.** This documentation was auto-generated\n"
    "> from the codebase and may contain inaccuracies. Please review and edit before relying on it.\n"
    "> Run `cortex accept` to remove this banner after review.\n\n"
)

DETAIL_LEVEL_INSTRUCTIONS = {
    "standard": "Keep content at a module-level summary. One paragraph per component.",
    "detailed": (
        "Include function/method-level docs. Document parameters, return types, "
        "error conditions, and usage examples."
    ),
    "comprehensive": (
        "Include everything from detailed plus: rationale for design decisions, "
        "mermaid architecture diagrams, performance implications, edge cases, "
        "and migration notes."
    ),
}


def _build_system_prompt(detail_level: str = "standard", existing_pages: list[str] | None = None) -> str:
    detail_instructions = DETAIL_LEVEL_INSTRUCTIONS.get(detail_level, DETAIL_LEVEL_INSTRUCTIONS["standard"])

    pages_note = ""
    if existing_pages:
        pages_list = ", ".join(existing_pages)
        pages_note = f"""
IMPORTANT: The only documentation pages that currently exist are: {pages_list}
Do NOT reference or link to pages that do not exist. If you want to mention a topic
that doesn't have its own page yet, describe it inline instead of linking to a non-existent file."""

    return f"""You are a technical documentation writer. Generate documentation content
for the specified sections based on code analysis.

Detail level: {detail_level}
{detail_instructions}
{pages_note}

When updating an existing section:
- Preserve the section's heading level and format
- Output ONLY the section body content (not the heading itself)
- Be concise and actionable

When creating a new page:
- Output the full page content in markdown
- Include appropriate headings structure
- Use markdown headings, lists, and code blocks

Focus on architecture decisions, component relationships, API contracts, and how things interact."""


PRESERVATION_PROMPT = """The following section has been manually edited by a developer.
Update it to reflect the code changes below, but PRESERVE any manual additions,
corrections, or stylistic choices that are not contradicted by the new code.
Do not discard human-written content unless it is factually incorrect."""


class DocWriterAgent(BaseAgent):
    """Generates documentation content and writes via DocBackend.

    Receives targeted_sections from SectionRouter, reads only those sections,
    generates updated content via LLM, and writes back through the backend.
    """

    async def run(self, state: CortexState) -> dict:
        analysis = state.get("analysis", "")
        if not analysis:
            return {"doc_updates": []}

        targeted_sections = state.get("targeted_sections", [])
        full_scan = state.get("full_scan", False)
        detail_level = state.get("detail_level", "standard")
        dry_run = state.get("dry_run", False)

        backend = self.backend or get_backend(self.settings)

        # Get existing page list so LLM doesn't hallucinate links
        try:
            existing_pages = [p.get("path", p.get("title", "")) for p in await backend.fetch_page_list()]
        except Exception:
            existing_pages = []

        related_docs = state.get("related_docs", [])
        related_context = ""
        if related_docs:
            related_context = "\n\n## Related Code\n"
            for doc in related_docs[:5]:
                related_context += f"\n### {doc.get('title', 'unknown')} (similarity: {doc.get('similarity', 0):.2f})\n"
                if doc.get("content"):
                    related_context += f"```\n{doc['content'][:1500]}\n```\n"

        doc_updates: list[DocUpdate] = []

        # Handle create_page actions
        create_pages = [s for s in targeted_sections if s.get("action") == "create_page"]
        update_sections = [s for s in targeted_sections if s.get("action") != "create_page"]

        # Generate new pages
        for page_spec in create_pages:
            title = page_spec.get("title", "Untitled")
            suggested_sections = page_spec.get("sections", [])
            reason = page_spec.get("reason", "")

            sections_hint = "\n".join(f"- {s}" for s in suggested_sections) if suggested_sections else ""
            prompt = f"""Create a new documentation page titled "{title}".

## Code Analysis
{analysis}
{related_context}

## Reason
{reason}

## Suggested Sections
{sections_hint}

Generate the full page content in markdown."""

            try:
                messages = [
                    {"role": "system", "content": _build_system_prompt(detail_level, existing_pages)},
                    {"role": "user", "content": prompt},
                ]
                content = await self._invoke_llm(messages, node_name="doc_writer")

                # Always add draft banner to new pages for human review
                content = DRAFT_BANNER + content

                if not dry_run:
                    page_ref = await backend.write_page("", title, content, "create")
                else:
                    page_ref = ""

                doc_updates.append(DocUpdate(
                    page_id=None,
                    page_path=page_ref,
                    title=title,
                    content=content,
                    action="create",
                    sections_updated=[],
                    validation_needed=True,
                ))
            except Exception as e:
                self._logger.warning(f"Failed to create page '{title}': {e}")

        # Update existing sections
        # Group by page to minimize backend calls
        from collections import defaultdict
        by_page: dict[str, list[dict]] = defaultdict(list)
        for section in update_sections:
            page = section.get("page", "")
            # Sanitize: LLM may return "docs/file.md" — strip leading docs/ prefix
            if page.startswith("docs/"):
                page = page[5:]
            if page:
                by_page[page].append(section)

        for page_ref, sections in by_page.items():
            sections_updated = []

            for section_spec in sections:
                heading = section_spec.get("section", "")
                reason = section_spec.get("reason", "")
                human_edited = section_spec.get("human_edited", False)

                # Read current section content
                existing_content = await backend.fetch_section(page_ref, heading)

                # Build prompt
                if human_edited and existing_content:
                    section_prompt = f"""{PRESERVATION_PROMPT}

## Current Section Content
```markdown
{existing_content[:2000]}
```

## Code Analysis
{analysis[:2000]}
{related_context}

## Why This Section Needs Updating
{reason}

Update the section content. Output ONLY the updated section body (no heading)."""
                else:
                    existing_hint = ""
                    if existing_content:
                        existing_hint = f"\n\n## Current Content\n```markdown\n{existing_content[:2000]}\n```"

                    section_prompt = f"""Generate updated content for the section "{heading}".

## Code Analysis
{analysis[:2000]}
{related_context}
{existing_hint}

## Why This Section Needs Updating
{reason}

Output ONLY the section body content (not the heading)."""

                try:
                    messages = [
                        {"role": "system", "content": _build_system_prompt(detail_level, existing_pages)},
                        {"role": "user", "content": section_prompt},
                    ]
                    new_content = await self._invoke_llm(messages, node_name="doc_writer")

                    if not dry_run:
                        await backend.write_section(page_ref, heading, new_content)

                    sections_updated.append(heading)
                except Exception as e:
                    self._logger.warning(f"Failed to update {heading} in {page_ref}: {e}")

            if sections_updated:
                doc_updates.append(DocUpdate(
                    page_id=None,
                    page_path=page_ref,
                    title=page_ref,
                    content="",  # Content written section-by-section
                    action="update",
                    sections_updated=sections_updated,
                    validation_needed=True,
                ))

        return {"doc_updates": doc_updates}
