"""TOCGenerator — deterministic node for TOC, meta index, and INDEX.md updates."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

from codebase_cortex.backends import get_backend
from codebase_cortex.backends.meta_index import MetaIndex
from codebase_cortex.config import Settings
from codebase_cortex.state import CortexState
from codebase_cortex.utils.section_parser import parse_sections

TOC_START = "<!-- cortex:toc -->"
TOC_END = "<!-- cortex:toc:end -->"


class TOCGeneratorAgent:
    """Deterministic node (no LLM) that maintains structural metadata.

    Responsibilities:
    1. Insert/update TOC markers in modified doc files
    2. Recompute content hashes and line ranges in .cortex-meta.json
    3. Regenerate INDEX.md
    4. Write run metrics
    """

    def __init__(self, settings: Settings | None = None) -> None:
        self.settings = settings

    async def run(self, state: CortexState) -> dict:
        settings = self.settings or Settings.from_env()
        backend = get_backend(settings)

        docs_dir = Path(settings.repo_path) / "docs"
        if not docs_dir.exists():
            return {}

        meta = None
        if hasattr(backend, "meta"):
            meta = backend.meta
        else:
            meta = MetaIndex(docs_dir)
            meta.load()

        # 1. Update TOC in modified files
        modified_pages = set()
        for update in state.get("validated_updates", state.get("doc_updates", [])):
            page_path = update.get("page_path") or update.get("title", "")
            if page_path:
                modified_pages.add(page_path)

        for md_file in docs_dir.glob("*.md"):
            if md_file.name.startswith("."):
                continue
            content = md_file.read_text()
            updated = self._update_toc(content)
            if updated != content:
                md_file.write_text(updated)

        # 2. Recompute content hashes for all sections
        meta.compute_content_hashes()

        # 3. Regenerate INDEX.md
        self._regenerate_index(docs_dir, meta, state)

        # 4. Write run metrics
        run_metrics = state.get("run_metrics", {})
        if run_metrics:
            meta.update_run_metrics(run_metrics)

        meta.save()
        return {}

    def _update_toc(self, content: str) -> str:
        """Insert or replace TOC between cortex:toc markers."""
        # Strip existing TOC before parsing to avoid counting TOC lines as sections
        clean_content = content
        if TOC_START in content and TOC_END in content:
            toc_pattern = re.escape(TOC_START) + r".*?" + re.escape(TOC_END)
            clean_content = re.sub(toc_pattern, "", content, flags=re.DOTALL).strip()

        sections = parse_sections(clean_content)
        if not sections:
            return content

        # Build TOC from headings
        toc_lines = []
        for section in sections:
            if not section.heading or section.level < 2:
                continue
            indent = "  " * (section.level - 2)
            display = section.heading.lstrip("#").strip()
            anchor = display.lower().replace(" ", "-")
            anchor = "".join(c for c in anchor if c.isalnum() or c == "-")
            toc_lines.append(f"{indent}- [{display}](#{anchor})")

        if not toc_lines:
            return content

        toc_block = f"{TOC_START}\n" + "\n".join(toc_lines) + f"\n{TOC_END}"

        # Replace existing TOC markers
        if TOC_START in content and TOC_END in content:
            pattern = re.escape(TOC_START) + r".*?" + re.escape(TOC_END)
            return re.sub(pattern, toc_block, content, flags=re.DOTALL)

        # Insert after first heading
        lines = content.split("\n")
        insert_idx = 0
        for i, line in enumerate(lines):
            if line.startswith("# "):
                insert_idx = i + 1
                # Skip blank lines after heading
                while insert_idx < len(lines) and not lines[insert_idx].strip():
                    insert_idx += 1
                break

        lines.insert(insert_idx, "\n" + toc_block + "\n")
        return "\n".join(lines)

    def _regenerate_index(
        self, docs_dir: Path, meta: MetaIndex, state: CortexState
    ) -> None:
        """Regenerate INDEX.md with page listing, recent changes, and task summary."""
        pages = meta.data.get("pages", {})
        tasks_meta = meta.data.get("tasks", {"total": 0, "by_priority": {}})
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        lines = [
            "# Documentation Index",
            "",
            f"*Auto-generated by Codebase Cortex · {now}*",
            "",
            "## Pages",
            "",
            "| Page | Sections | Last Updated |",
            "|------|----------|--------------|",
        ]

        for filename, page_data in sorted(pages.items()):
            title = page_data.get("title", filename)
            section_count = len(page_data.get("sections", []))
            last_updated = page_data.get("last_updated", "—")
            if last_updated and len(last_updated) > 10:
                last_updated = last_updated[:10]  # Just the date
            lines.append(f"| [{title}]({filename}) | {section_count} | {last_updated} |")

        # Recent changes
        doc_updates = state.get("validated_updates", state.get("doc_updates", []))
        if doc_updates:
            lines.extend([
                "",
                "## Recent Changes",
                "",
            ])
            for update in doc_updates[:10]:
                action = update.get("action", "update")
                title = update.get("title", "Untitled")
                lines.append(f"- **{action}**: {title}")

        # Task summary
        if tasks_meta.get("total", 0) > 0:
            lines.extend([
                "",
                "## Open Tasks",
                "",
                f"Total: {tasks_meta['total']}",
            ])
            for priority, count in tasks_meta.get("by_priority", {}).items():
                icon = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(priority, "⚪")
                lines.append(f"- {icon} {priority}: {count}")

        lines.append("")  # Final newline
        index_path = docs_dir / "INDEX.md"
        index_path.write_text("\n".join(lines))
